2021-06-25T17:49:42|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\SPIM-OPT\anaconda3\envs\scopefoundry_py38\lib\site-packages\ScopeFoundry\hardware.py", line 160, in <lambda>
    op_button.clicked.connect(lambda checked, f=op_func: f())
  File "D:\LabPrograms\ScopeFoundry_POLIMI\PI_ScopeFoundry\PI_CG_hardware.py", line 69, in stop
    self.motor.stop()
  File "D:\LabPrograms\ScopeFoundry_POLIMI\PI_ScopeFoundry\PI_CG_device.py", line 83, in stop
    self.pi_device.HLT(self.axis)
  File "D:\LabPrograms\ScopeFoundry_POLIMI\PI_ScopeFoundry\PIPython\pipython\pidevice\gcs2\gcs2commands.py", line 1058, in HLT
    self._msgs.send(cmdstr)
  File "D:\LabPrograms\ScopeFoundry_POLIMI\PI_ScopeFoundry\PIPython\pipython\pidevice\gcsmessages.py", line 107, in send
    self._checkerror(senderr=not self.embederr)
  File "D:\LabPrograms\ScopeFoundry_POLIMI\PI_ScopeFoundry\PIPython\pipython\pidevice\gcsmessages.py", line 302, in _checkerror
    raise exc  # Raising NoneType while only classes or instances are allowed pylint: disable=E0702
PI_ScopeFoundry.PIPython.pipython.pidevice.gcserror.GCSError: Controller was stopped by command (10)

