2021-06-21T15:55:39|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\SPIM-OPT\anaconda3\envs\scopefoundry_py38\lib\site-packages\ScopeFoundry\hardware.py", line 219, in enable_connection
    raise err
  File "C:\Users\SPIM-OPT\anaconda3\envs\scopefoundry_py38\lib\site-packages\ScopeFoundry\hardware.py", line 212, in enable_connection
    self.disconnect()
  File "D:\LabPrograms\ScopeFoundry_POLIMI\PI_ScopeFoundry\PI_CG_hardware.py", line 47, in disconnect
    self.motor.close()
  File "D:\LabPrograms\ScopeFoundry_POLIMI\PI_ScopeFoundry\PI_CG_device.py", line 85, in close
    self.pi_device.stop()
AttributeError: 'GCS2Device' object has no attribute 'stop'

